### ISSUE TITLE
Port to Hubitat Elevation

### ISSUE THREAD

**Issue by mayhew132** [fison67/LG-Connector#13]
Hi there,

I've been using your SmartApp and DTH for linking my ThinQ devices to SmartThings, however I've now moved to Hubitat Elevation after the messy migration from ST 'Classic' to 'New' app - would it be possible to port this code over to HE please?

**Comment by fison67** [comment]
Sorry, I have a no plan.

**Comment by mayhew132** [comment]
Thanks for letting us know - in case anyone else comes here looking for a HE App and Driver that achieves the same result see here: https://github.com/dcmeglio/hubitat-thinq

This doesn't require an intermediate server either, so is all contained in the same App installed on the Hubitat Hub.
