### ISSUE TITLE
Settings for UK (en-gb) Smart ThinQ Users

### ISSUE THREAD

**Issue by mayhew132** [fison67/LG-Connector#2]
Hi,

Firstly, thanks for developing this integration - it's really useful for people like me who aren't familiar with coding but have an interest in Smart Home technologies.

For anyone else who, like me, have a UK LG account please find below the settings which will need to be entered into the lg-config.json file in the config subfolder **(changes in bold**):

> {
>   "system": {
>     "mode": "Auto",
>     "address": "IP_ADDRESS",
>     "port": "PORT"
>   },
>   "user": {
>     "name": "admin",
>     "password": "12345"
>   },
>   "st": {
>     "app_url": "https://graph-eu01-euwest1.api.smartthings.com:443/api/smartapps/installations/",
>     "app_id": "APPIDFROMST",
>     "access_token": "APPTOKENFROMST"
>   },
>   "smartthinq": {
>     "refresh_token": "REFRESHTOKENGENERATED",
**>     "auth_base": "https://gb.m.lgaccount.com",
>     "api_root": "https://eic.lgthinq.com:46030/api",
>     "oauth_root": "https://gb.lgeapi.com"**
>   },
>   "token": "APPTOKENGENERATED",
>   "devices": {
>     "list": []
>   },
>   **"preset": {
>     "country": "GB",
>     "language": "en-US"**
>   },
>   "pollingTime": 1
> }

Once you have replaced the lg-config.json file with these tweaks restart docker and your LG appliance should be detected (in my case a Washer Dryer).

Best wishes,
Guy

**Comment by cjattard** [comment]
I might be being rather dim - as there is no package editor within the docker container how does one go about editing the lg-config.json file. I cant seem to be able to browse to the location in terminal via SSH either as the volume has no contents when browsed from host. I can see the file within the container via terminal though.
